apiVersion: apps/v1 
kind: Deployment
metadata:
  name: carvilla
  labels: 
     app: carvilla

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: carvilla

  template:
    metadata:
      labels:
        app: carvilla
    spec:
      containers:
      - name: carvilla
        image: vaninoel/carvilla:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

--
apiVersion: v1
kind: Service
metadata:
  name: carvilla
  labels: 
    app: carvilla

spec:
  selector:
    app: carvilla
  
  ports:
    - port: 8081
      targetPort: 8081
  
  type: LoadBalancer